# JWT Secret Key
jwt.secret=MYHtL+q99goBjY1HlWA3E6WxsWZlakEDz7a5IOxXJX8ncU0Uu61OT5ZPLgagx6NKtxJNdtS1GBX9Imyy/QY97A==

# CoolSMS (Solapi) API Keys
coolsms.api.key=NCSCCDT2TTED6QX7
coolsms.api.secret=NUQRA5JQLXXLQDOSHFE1AWUVBEXUHVKG

# Gmail App Password
spring.mail.password=vupzryyixjdyrvwz