server.port=8090

# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/govengers?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=skgus1202!

# JPA Configuration
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.sql.init.mode=never

spring.profiles.active=macos
custom.upload-path=/Users/minhopark/Documents/Java/govengers/gogiImage

# file size configuration
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

server.tomcat.max-http-form-post-size=10MB

# JWT - ?? ???? ??? ??!
jwt.secret=MYHtL+q99goBjY1HlWA3E6WxsWZlakEDz7a5IOxXJX8ncU0Uu61OT5ZPLgagx6NKtxJNdtS1GBX9Imyy/QY97A==
jwt.accessTokenExpirationTime=3600000
jwt.refreshTokenExpirationTime=86400000

# Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=idelleene@gmail.com
spring.mail.password=vupzryyixjdyrvwz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMS
coolsms.from.phone=01093853085

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# secret
spring.profiles.include=secret